language: swift

osx_image: xcode9

xcode_sdk: iphonesimulator10.0

install:
  - ./Scripts/install_swiftlint.sh

script:
  - set -o pipefail
  - swiftlint --strict
  - swift package update
  - xcodebuild -project Trck.xcodeproj -scheme "Trck-Package" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty